baseurl: "https://qijiahe.netlify.app/"
languageCode: "en-us"
title: "Qijia He's HomePage"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
footnotereturnlinkcontents: "↩"
menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Gallary
      url: "gallary/"
      weight: 3
    - name: FunFact
      url: "funfact/"
      weight: 4

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [QIJIA HE](https://yihui.org) 2023 -- {Year} | [Github](https://github.com/HermioneHQJ)"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
